version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - run:
          name: setup
          command: |
            rustup install nightly-2019-11-25
            rustup component add rustfmt --toolchain nightly-2019-11-25
            rustup component add clippy --toolchain nightly-2019-11-25

      - run:
          name: fmt
          command: |
            cargo +nightly-2019-11-25 fmt --version
            cargo +nightly-2019-11-25 fmt --all -- --check

      - run:
          name: clippy
          command: |
            cargo +nightly-2019-11-25 clippy --version
            cargo +nightly-2019-11-25 clippy --all -- -D warnings

      - run:
          name: build
          command: |
            cargo --version --verbose
            cargo build --all
            cargo build --all --no-default-features

      - run:
          name: unit tests
          command: |
            cargo test --all

      - run:
          name: no-std tests
          command: |
            cd ./test_suite/derive_tests_no_std
            cargo +nightly-2019-11-25 build --no-default-features

workflows:
  version: 2
  run-build:
    jobs:
      - build
